[package]
name = "amethyst-inspector"
version = "0.1.0"
edition = "2018"

[dependencies]
amethyst = { git = "https://github.com/amethyst/amethyst.git" }
amethyst-imgui = { git = "https://github.com/awpteamoose/amethyst-imgui.git" }
amethyst-inspector-derive = { path = "amethyst-inspector-derive" }
matches = "0.1"
paste = "0.1"
automod = { git = "https://github.com/Awpteamoose/automod" }
specs-derive = "0.4"

[features]
saveload = []
